LoadModule ssl_module modules/mod_ssl.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

<VirtualHost *:80>
    DocumentRoot "C:/ospanel/domains/smart-parking-new/client"
    ServerName lk.npo-nauka.ru
    ServerAlias www.lk.npo-nauka.ru
    Redirect permanent / https://lk.npo-nauka.ru/
</VirtualHost>

<IfModule ssl_module>
    <VirtualHost *:443>
        DocumentRoot "C:/ospanel/domains/smart-parking-new/client"
        ServerName lk.npo-nauka.ru
        ServerAlias www.lk.npo-nauka.ru

        SSLEngine on
        SSLCertificateFile    "C:/win-acme/lk.pro-nauka/lk.npo-nauka.ru-crt.pem"
        SSLCertificateKeyFile "C:/win-acme/lk.pro-nauka/lk.npo-nauka.ru-key.pem"
        SSLCertificateChainFile "C:/win-acme/lk.pro-nauka/lk.npo-nauka.ru-chain.pem"
        # SSLCertificateFile "C:/ospanel/userdata\config\cert_files\lk.npo-nauka\lk.npo-nauka-server.crt"
        # SSLCertificateKeyFile "C:/ospanel/userdata\config\cert_files\lk.npo-nauka\lk.npo-nauka-server.key"


		ProxyRequests Off
        ProxyPass /api/ http://84.47.169.58:5000/
        ProxyPassReverse /api/ http://84.47.169.58:5000/

        # Proxy WebSocket connections
        ProxyPass /socket.io/ ws://localhost:4000/socket.io/
        ProxyPassReverse /socket.io/ ws://localhost:4000/socket.io/

        # Proxy WebSocket connections (alternative for all WebSocket routes)
        ProxyPassMatch "^/(.*)/(.*\.ws)$"  ws://localhost:4000/$1/$2
        ProxyPassReverse "^/(.*)/(.*\.ws)$"  ws://localhost:4000/$1/$2

        <Proxy *>
            Order deny,allow
            Allow from all
        </Proxy>
    </VirtualHost>
</IfModule>
