// auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_LOADING_START = "LOGIN_LOADING_START"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_LOADING_START = "UPDATE_PROFILE_LOADING_START"
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR"

export const LOGOUT_USER  = "LOGOUT_USER"


// users
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_LOADING_START = "GET_USERS_LOADING_START"
export const GET_USERS_ERROR = "GET_USERS_ERROR"


export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS"
export const ADD_USERS_LOADING_START = "ADD_USERS_LOADING_START"
export const ADD_USERS_ERROR = "ADD_USERS_ERROR"

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_LOADING_START = "DELETE_USER_LOADING_START"
export const DELETE_USER_ERROR = "DELETE_USER_ERROR"

export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"
export const EDIT_USER_LOADING_START = "EDIT_USER_LOADING_START"
export const EDIT_USER_ERROR = "EDIT_USER_ERROR"

export const RESET_USER_STATE = "RESET_USER_STATE"

export const SET_USERS_PAGE = "SET_USERS_PAGE"


// tenants
export const GET_TENANTS_SUCCESS = "GET_TENANTS_SUCCESS"
export const GET_TENANTS_LOADING_START = "GET_TENANTS_LOADING_START"
export const GET_TENANTS_ERROR = "GET_TENANTS_ERROR"

export const ADD_TENANT_SUCCESS = "ADD_TENANT_SUCCESS"
export const ADD_TENANT_LOADING_START = "ADD_TENANT_LOADING_START"
export const ADD_TENANT_ERROR = "ADD_TENANT_ERROR"

export const DELETE_TENANT_SUCCESS = "DELETE_TENANT_SUCCESS"
export const DELETE_TENANT_LOADING_START = "DELETE_TENANT_LOADING_START"
export const DELETE_TENANT_ERROR = "DELETE_TENANT_ERROR"

export const EDIT_TENANT_SUCCESS = "EDIT_TENANT_SUCCESS"
export const EDIT_TENANT_LOADING_START = "EDIT_TENANT_LOADING_START"
export const EDIT_TENANT_ERROR = "EDIT_TENANT_ERROR"

export const GET_TENANT_NAME_LIST_SUCCESS = "GET_TENANT_NAME_LIST_SUCCESS"
export const GET_TENANT_NAME_LIST_LOADING_START = "GET_TENANT_NAME_LIST_LOADING_START"
export const GET_TENANT_NAME_LIST_ERROR = "GET_TENANT_NAME_LIST_ERROR"

export const RESET_TENANT_SUCCESS = "RESET_TENANT_SUCCESS"
export const RESET_TENANT_LOADING_START = "RESET_TENANT_LOADING_START"
export const RESET_TENANT_ERROR = "RESET_TENANT_ERROR"

export const SET_TENANTS_PAGE = "SET_TENANTS_PAGE"


// employees
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS"
export const GET_EMPLOYEES_LOADING_START = "GET_EMPLOYEES_LOADING_START"
export const GET_EMPLOYEES_ERROR = "GET_EMPLOYEES_ERROR"

export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS"
export const ADD_EMPLOYEE_LOADING_START = "ADD_EMPLOYEE_LOADING_START"
export const ADD_EMPLOYEE_ERROR = "ADD_EMPLOYEE_ERROR"

export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS"
export const DELETE_EMPLOYEE_LOADING_START = "DELETE_EMPLOYEE_LOADING_START"
export const DELETE_EMPLOYEE_ERROR = "DELETE_EMPLOYEE_ERROR"

export const EDIT_EMPLOYEE_SUCCESS = "EDIT_EMPLOYEE_SUCCESS"
export const EDIT_EMPLOYEE_LOADING_START = "EDIT_EMPLOYEE_LOADING_START"
export const EDIT_EMPLOYEE_ERROR = "EDIT_EMPLOYEE_ERROR"

export const SET_EMPLOYEES_PAGE = "SET_EMPLOYEES_PAGE"


// parking
export const GET_PARKING_SUCCESS = "GET_PARKING_SUCCESS"
export const GET_PARKING_LOADING_START = "GET_PARKING_LOADING_START"
export const GET_PARKING_ERROR = "GET_PARKING_ERROR"

export const SET_PARKING_PAGE = "SET_PARKING_PAGE"

// history
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS"
export const GET_HISTORY_LOADING_START = "GET_HISTORY_LOADING_START"
export const GET_HISTORY_ERROR = "GET_HISTORY_ERROR"

export const SET_HISTORY_PAGE = "SET_HISTORY_PAGE"
